/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "data-manage_basic": () => import("@/views/data-manage/basic/index.vue"),
  "data-manage_business": () => import("@/views/data-manage/business/index.vue"),
  "data-manage_finance": () => import("@/views/data-manage/finance/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "permission-manage_menu": () => import("@/views/permission-manage/menu/index.vue"),
  "permission-manage_role": () => import("@/views/permission-manage/role/index.vue"),
  "permission-manage_user": () => import("@/views/permission-manage/user/index.vue"),
  "system-manage_customer": () => import("@/views/system-manage/customer/index.vue"),
  "system-manage_group": () => import("@/views/system-manage/group/index.vue"),
  "system-manage_label-designer": () => import("@/views/system-manage/label-designer/index.vue"),
  "system-manage_print-design": () => import("@/views/system-manage/print-design/index.vue"),
  "system-manage_setting": () => import("@/views/system-manage/setting/index.vue"),
  "system-manage_site": () => import("@/views/system-manage/site/index.vue"),
};
