/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

/**
 * All generated routes (literal, kept for the elegant-router vite plugin).
 *
 * NOTE: the plugin parses this export on startup
 * (`JSON.parse(JSON.stringify(n.exports.generatedRoutes))`) to merge newly
 * scanned routes and preserve hand-added meta (icon/order). It MUST stay a
 * literal array — composing it from other arrays (spread / concat) breaks the
 * plugin. It is auto-updated on regeneration.
 */
export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'channel-quote',
    path: '/channel-quote',
    component: 'layout.base',
    meta: {
      title: 'channel-quote',
      i18nKey: 'route.channel-quote',
      order: 2,
      icon: 'ic:baseline-sell',
      keepAlive: true
    },
    children: [
      {
        name: 'channel-quote_receive',
        path: '/channel-quote/receive',
        component: 'view.channel-quote_receive',
        meta: {
          title: 'channel-quote_receive',
          i18nKey: 'route.channel-quote_receive',
          icon: 'ic:baseline-move-to-inbox',
          permission: 'system:channelQuote:receive:list',
          keepAlive: true
        }
      },
      {
        name: 'channel-quote_ship',
        path: '/channel-quote/ship',
        component: 'view.channel-quote_ship',
        meta: {
          title: 'channel-quote_ship',
          i18nKey: 'route.channel-quote_ship',
          icon: 'ic:baseline-local-shipping',
          permission: 'system:channelQuote:ship:list',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'customer-manage',
    path: '/customer-manage',
    component: 'layout.base',
    meta: {
      title: 'customer-manage',
      i18nKey: 'route.customer-manage',
      icon: 'ic:round-business',
      order: 1,
      keepAlive: true
    },
    children: [
      {
        name: 'customer-manage_customer',
        path: '/customer-manage/customer',
        component: 'view.customer-manage_customer',
        meta: {
          title: 'customer-manage_customer',
          i18nKey: 'route.customer-manage_customer',
          icon: 'ic:round-contacts',
          order: 1,
          permission: 'system:customer:list',
          keepAlive: true
        }
      },
      {
        name: 'customer-manage_customer-level',
        path: '/customer-manage/customer-level',
        component: 'view.customer-manage_customer-level',
        meta: {
          title: 'customer-manage_customer-level',
          i18nKey: 'route.customer-manage_customer-level',
          keepAlive: true,
          icon: 'ic:round-stars',
          order: 2,
          permission: 'system:customerLevel:list'
        }
      },
      {
        name: 'customer-manage_customer-source',
        path: '/customer-manage/customer-source',
        component: 'view.customer-manage_customer-source',
        meta: {
          title: 'customer-manage_customer-source',
          i18nKey: 'route.customer-manage_customer-source',
          keepAlive: true,
          icon: 'ic:round-ads-click',
          order: 3,
          permission: 'system:customerSource:list'
        }
      }
    ]
  },
  {
    name: 'data-manage',
    path: '/data-manage',
    component: 'layout.base',
    meta: {
      title: 'data-manage',
      i18nKey: 'route.data-manage',
      icon: 'ic:baseline-folder',
      order: 3,
      keepAlive: true
    },
    children: [
      {
        name: 'data-manage_basic',
        path: '/data-manage/basic',
        component: 'view.data-manage_basic',
        meta: {
          title: 'data-manage_basic',
          i18nKey: 'route.data-manage_basic',
          icon: 'ic:baseline-inventory',
          order: 6,
          permission: 'system:basic:list',
          keepAlive: true
        }
      },
      {
        name: 'data-manage_bl',
        path: '/data-manage/bl',
        component: 'view.data-manage_bl',
        meta: {
          title: 'data-manage_bl',
          i18nKey: 'route.data-manage_bl',
          order: 5,
          icon: 'ic:baseline-receipt-long',
          permission: 'system:bl:list',
          keepAlive: true
        }
      },
      {
        name: 'data-manage_business',
        path: '/data-manage/business',
        component: 'view.data-manage_business',
        meta: {
          title: 'data-manage_business',
          i18nKey: 'route.data-manage_business',
          icon: 'ic:baseline-warehouse',
          order: 3,
          permission: 'system:business:list',
          keepAlive: true
        }
      },
      {
        name: 'data-manage_finance',
        path: '/data-manage/finance',
        component: 'view.data-manage_finance',
        meta: {
          title: 'data-manage_finance',
          i18nKey: 'route.data-manage_finance',
          icon: 'ic:baseline-account-balance-wallet',
          order: 4,
          permission: 'system:finance:list',
          keepAlive: true
        }
      },
      {
        name: 'data-manage_no-rule',
        path: '/data-manage/no-rule',
        component: 'view.data-manage_no-rule',
        meta: {
          title: 'data-manage_no-rule',
          i18nKey: 'route.data-manage_no-rule',
          icon: 'ic:round-numbers',
          order: 2,
          permission: 'system:noRule:list',
          keepAlive: true
        }
      },
      {
        name: 'data-manage_ship',
        path: '/data-manage/ship',
        component: 'view.data-manage_ship',
        meta: {
          title: 'data-manage_ship',
          i18nKey: 'route.data-manage_ship',
          icon: 'ic:baseline-local-shipping',
          order: 1,
          permission: 'system:ship:list',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 0,
      keepAlive: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'system-manage',
    path: '/system-manage',
    component: 'layout.base',
    meta: {
      title: 'system-manage',
      i18nKey: 'route.system-manage',
      icon: 'ic:baseline-settings',
      order: 4,
      keepAlive: true
    },
    children: [
      {
        name: 'system-manage_group',
        path: '/system-manage/group',
        component: 'view.system-manage_group',
        meta: {
          title: 'system-manage_group',
          i18nKey: 'route.system-manage_group',
          icon: 'ic:round-groups',
          order: 3,
          permission: 'system:group:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_label-designer',
        path: '/system-manage/label-designer',
        component: 'view.system-manage_label-designer',
        meta: {
          title: 'system-manage_label-designer',
          i18nKey: 'route.system-manage_label-designer',
          hideInMenu: true,
          activeMenu: 'system-manage_setting',
          icon: 'ic:round-label',
          order: 6,
          permission: 'system:labelDesign:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_log',
        path: '/system-manage/log',
        component: 'view.system-manage_log',
        meta: {
          title: 'system-manage_log',
          i18nKey: 'route.system-manage_log',
          icon: 'ic:round-article',
          order: 6,
          permission: 'system:log:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_print-design',
        path: '/system-manage/print-design',
        component: 'view.system-manage_print-design',
        meta: {
          title: 'system-manage_print-design',
          i18nKey: 'route.system-manage_print-design',
          hideInMenu: true,
          permission: 'system:printDesign:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_role',
        path: '/system-manage/role',
        component: 'view.system-manage_role',
        meta: {
          title: 'system-manage_role',
          i18nKey: 'route.system-manage_role',
          icon: 'ic:round-supervisor-account',
          order: 2,
          permission: 'system:role:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_setting',
        path: '/system-manage/setting',
        component: 'view.system-manage_setting',
        meta: {
          title: 'system-manage_setting',
          i18nKey: 'route.system-manage_setting',
          icon: 'ic:baseline-settings-applications',
          order: 5,
          permission: 'system:setting:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_site',
        path: '/system-manage/site',
        component: 'view.system-manage_site',
        meta: {
          title: 'system-manage_site',
          i18nKey: 'route.system-manage_site',
          icon: 'ic:round-place',
          order: 4,
          permission: 'system:site:list',
          keepAlive: true
        }
      },
      {
        name: 'system-manage_user',
        path: '/system-manage/user',
        component: 'view.system-manage_user',
        meta: {
          title: 'system-manage_user',
          i18nKey: 'route.system-manage_user',
          icon: 'ic:round-person',
          order: 1,
          permission: 'system:user:list',
          keepAlive: true
        }
      }
    ]
  }
];

/** A route is non-menu when it is constant or explicitly hidden from the menu. */
const isNonMenuRoute = (route: GeneratedRoute): boolean =>
  Boolean(route.meta?.constant) || Boolean(route.meta?.hideInMenu);

/** Non-menu routes (constant / hideInMenu) — derived from `generatedRoutes`. */
export const nonMenuRoutes = generatedRoutes.filter(isNonMenuRoute);

/** Menu routes (shown in the sidebar) — derived from `generatedRoutes`. */
export const menuRoutes = generatedRoutes.filter(route => !isNonMenuRoute(route));
