/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

/**
 * All generated routes (literal, kept for the elegant-router vite plugin).
 *
 * NOTE: the plugin parses this export on startup
 * (`JSON.parse(JSON.stringify(n.exports.generatedRoutes))`) to merge newly
 * scanned routes and preserve hand-added meta (icon/order). It MUST stay a
 * literal array — composing it from other arrays (spread / concat) breaks the
 * plugin. It is auto-updated on regeneration.
 */
export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'data-manage',
    path: '/data-manage',
    component: 'layout.base',
    meta: {
      title: 'data-manage',
      i18nKey: 'route.data-manage',
      icon: 'ic:baseline-folder',
      order: 1
    },
    children: [
      {
        name: 'data-manage_basic',
        path: '/data-manage/basic',
        component: 'view.data-manage_basic',
        meta: {
          title: 'data-manage_basic',
          i18nKey: 'route.data-manage_basic',
          icon: 'ic:baseline-inventory'
        }
      },
      {
        name: 'data-manage_business',
        path: '/data-manage/business',
        component: 'view.data-manage_business',
        meta: {
          title: 'data-manage_business',
          i18nKey: 'route.data-manage_business',
          icon: 'ic:baseline-warehouse'
        }
      },
      {
        name: 'data-manage_finance',
        path: '/data-manage/finance',
        component: 'view.data-manage_finance',
        meta: {
          title: 'data-manage_finance',
          i18nKey: 'route.data-manage_finance',
          icon: 'ic:baseline-account-balance-wallet'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'permission-manage',
    path: '/permission-manage',
    component: 'layout.base',
    meta: {
      title: 'permission-manage',
      i18nKey: 'route.permission-manage',
      icon: 'ic:round-lock',
      order: 3
    },
    children: [
      {
        name: 'permission-manage_menu',
        path: '/permission-manage/menu',
        component: 'view.permission-manage_menu',
        meta: {
          title: 'permission-manage_menu',
          i18nKey: 'route.permission-manage_menu',
          icon: 'ic:baseline-menu',
          order: 3
        }
      },
      {
        name: 'permission-manage_role',
        path: '/permission-manage/role',
        component: 'view.permission-manage_role',
        meta: {
          title: 'permission-manage_role',
          i18nKey: 'route.permission-manage_role',
          icon: 'ic:round-supervisor-account',
          order: 2
        }
      },
      {
        name: 'permission-manage_user',
        path: '/permission-manage/user',
        component: 'view.permission-manage_user',
        meta: {
          title: 'permission-manage_user',
          i18nKey: 'route.permission-manage_user',
          icon: 'ic:round-person',
          order: 1
        }
      }
    ]
  },
  {
    name: 'system-manage',
    path: '/system-manage',
    component: 'layout.base',
    meta: {
      title: 'system-manage',
      i18nKey: 'route.system-manage',
      icon: 'ic:baseline-settings',
      order: 2
    },
    children: [
      {
        name: 'system-manage_customer',
        path: '/system-manage/customer',
        component: 'view.system-manage_customer',
        meta: {
          title: 'system-manage_customer',
          i18nKey: 'route.system-manage_customer',
          icon: 'ic:round-business',
          order: 6
        }
      },
      {
        name: 'system-manage_group',
        path: '/system-manage/group',
        component: 'view.system-manage_group',
        meta: {
          title: 'system-manage_group',
          i18nKey: 'route.system-manage_group',
          icon: 'ic:round-groups',
          order: 5
        }
      },
      {
        name: 'system-manage_label-designer',
        path: '/system-manage/label-designer',
        component: 'view.system-manage_label-designer',
        meta: {
          title: 'system-manage_label-designer',
          i18nKey: 'route.system-manage_label-designer',
          hideInMenu: true,
          activeMenu: 'system-manage_setting',
          icon: 'ic:round-label',
          order: 6
        }
      },
      {
        name: 'system-manage_print-design',
        path: '/system-manage/print-design',
        component: 'view.system-manage_print-design',
        meta: {
          title: 'system-manage_print-design',
          i18nKey: 'route.system-manage_print-design',
          hideInMenu: true
        }
      },
      {
        name: 'system-manage_setting',
        path: '/system-manage/setting',
        component: 'view.system-manage_setting',
        meta: {
          title: 'system-manage_setting',
          i18nKey: 'route.system-manage_setting',
          icon: 'ic:baseline-settings-applications',
          order: 7
        }
      },
      {
        name: 'system-manage_site',
        path: '/system-manage/site',
        component: 'view.system-manage_site',
        meta: {
          title: 'system-manage_site',
          i18nKey: 'route.system-manage_site',
          icon: 'ic:round-place',
          order: 4
        }
      }
    ]
  }
];

/** A route is non-menu when it is constant or explicitly hidden from the menu. */
const isNonMenuRoute = (route: GeneratedRoute): boolean =>
  Boolean(route.meta?.constant) || Boolean(route.meta?.hideInMenu);

/** Non-menu routes (constant / hideInMenu) — derived from `generatedRoutes`. */
export const nonMenuRoutes = generatedRoutes.filter(isNonMenuRoute);

/** Menu routes (shown in the sidebar) — derived from `generatedRoutes`. */
export const menuRoutes = generatedRoutes.filter(route => !isNonMenuRoute(route));
